# Generated by Django 4.1.1 on 2022-09-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('modeltype', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('new', models.CharField(max_length=30)),
                ('used', models.CharField(max_length=30)),
                ('finaced', models.CharField(max_length=30)),
                ('cash', models.CharField(max_length=30)),
            ],
        ),
    ]
